# Generated by Django 6.1.1 on 2026-09-17 11:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pep", "0003_clinicalevolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("specimen_type", models.CharField(max_length=100, verbose_name="Material")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "ordering": ["name", "code"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("test_code", models.CharField(max_length=64)),
                ("test_name", models.CharField(max_length=200)),
                ("specimen_type", models.CharField(max_length=100)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("operation_key", models.UUIDField(unique=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pep.encounter"
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="lis.labtest"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "permissions": [
                    ("view_orders", "Pode consultar pedidos laboratoriais"),
                    ("order_test", "Pode solicitar exame"),
                    ("collect_specimen", "Pode registrar coleta"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("accession_code", models.CharField(max_length=64, unique=True)),
                ("collected_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("operation_key", models.UUIDField(unique=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "service_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="lis.servicerequest"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["-requested_at", "-id"], name="lis_requested_idx"),
        ),
    ]
