services:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  aegis_share:
    build: .
    entrypoint: ["/bin/sh", "/app/commands.sh"]
    environment:
      - DOCKER_ENV=true
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - redis
