[project]
name = "proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argon2-cffi>=25.1.0",
    "channels>=4.3.2",
    "channels-redis>=4.3.0",
    "crispy-bulma>=0.12.0",
    "django>=5.2.17",
    "django-crispy-forms>=2.7",
    "django-feather>=0.3.0",
    "django-htmx>=1.29.0",
    "django-simple-bulma>=2.7.1",
    "granian>=2.8.2",
    "pillow>=12.3.0",
    "pillow-avif-plugin>=1.6.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "granian[reload]>=2.8.2",
    "taskipy>=1.14.1",
    "isort>=9.0.1",
]

[tool.ruff]
exclude = [
    "venv/",
    ".venv/",
    "env/",
    ".env/",
    "build/",
    "dist/",
    "*.egg-info/",
    "*.db",
    "*.sqlite3",
    "*.log",
    "aegis_share/models.py",
    "aegis_share/migrations/",
    "test_tmp_*",
]

[tool.taskipy.tasks]
fmt = 'isort . && ruff check --fix && ruff format'
server = 'granian mysite.asgi:application  --interface asgi --host 0.0.0.0 --port 8000'
migrate = 'uv run manage.py makemigrations && uv run manage.py migrate'
