# Generated by Django 6.1.1 on 2026-09-18 16:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("unit", models.CharField(max_length=40, verbose_name="Unidade de contagem")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_code", models.CharField(max_length=64)),
                ("item_name", models.CharField(max_length=200)),
                ("item_unit", models.CharField(max_length=40)),
                ("quantity", models.PositiveIntegerField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("operation_key", models.UUIDField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.inventoryitem"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "permissions": [
                    ("view_requisitions", "Pode consultar catálogo e requisições institucionais"),
                    ("request_material", "Pode requisitar material"),
                ],
                "indexes": [
                    models.Index(fields=["-requested_at", "-id"], name="inventory_req_created_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation_key",), name="uniq_inventory_req_operation"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1), ("quantity__lte", 999999)),
                        name="inventory_req_qty_range",
                    ),
                ],
            },
        ),
    ]
