# Generated by Django 6.1.1 on 2026-09-18 16:27

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pep", "0003_clinicalevolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("operation_key", models.UUIDField()),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="pep.encounter"
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at", "-id"],
                "permissions": [
                    ("view_accounts", "Pode consultar contas em preparação"),
                    ("open_account", "Pode abrir conta em preparação"),
                    ("add_item", "Pode lançar item manual"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("operation_key", models.UUIDField()),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="billing.hospitalaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="hospitalaccount",
            index=models.Index(fields=["-opened_at", "-id"], name="billing_account_opened_idx"),
        ),
        migrations.AddConstraint(
            model_name="hospitalaccount",
            constraint=models.UniqueConstraint(
                fields=("operation_key",), name="uniq_billing_account_operation"
            ),
        ),
        migrations.AddIndex(
            model_name="billingitem",
            index=models.Index(
                fields=["account", "-recorded_at", "-id"], name="billing_item_account_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingitem",
            constraint=models.UniqueConstraint(
                fields=("operation_key",), name="uniq_billing_item_operation"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 999999)),
                name="billing_item_quantity_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_price__gte", 0), ("unit_price__lte", Decimal("9999999999.99"))
                ),
                name="billing_item_price_range",
            ),
        ),
    ]
