# Generated by Django 6.1.1 on 2026-09-16 15:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pep", "0003_clinicalevolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Acesso"),
                            ("CORRECTION", "Correção"),
                            ("DELETION", "Exclusão"),
                            ("PORTABILITY", "Portabilidade"),
                            ("OTHER", "Outra"),
                        ],
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recebida"),
                            ("IN_REVIEW", "Em análise"),
                            ("CLOSED", "Encerrada administrativamente"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pep.patient"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("view_requests", "Pode consultar solicitações do titular"),
                    ("register_request", "Pode registrar solicitações do titular"),
                    ("process_request", "Pode processar solicitações do titular"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequestEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVED", "Recebida"),
                            ("IN_REVIEW", "Em análise"),
                            ("CLOSED", "Encerrada administrativamente"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recebida"),
                            ("IN_REVIEW", "Em análise"),
                            ("CLOSED", "Encerrada administrativamente"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="compliance.datasubjectrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="datasubjectrequest",
            index=models.Index(fields=["status", "created_at"], name="lgp_status_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="datasubjectrequestevent",
            constraint=models.UniqueConstraint(
                fields=("request", "to_status"), name="uniq_lgp_request_state"
            ),
        ),
    ]
