# Generated by Django 5.2.6 on 2025-10-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aegis_share", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="cpf",
        ),
        migrations.AddField(
            model_name="customuser",
            name="telefone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="ipfsfile",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipfsfile",
            name="pinata_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID do Pinata"
            ),
        ),
    ]
