# Generated by Django 6.1.1 on 2026-09-18 15:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pep", "0003_clinicalevolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingExam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ImagingOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("exam_code", models.CharField(max_length=64)),
                ("exam_name", models.CharField(max_length=200)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("operation_key", models.UUIDField()),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pep.encounter"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ris.imagingexam"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "permissions": [
                    ("view_orders", "Pode consultar pedidos de imagem"),
                    ("order_exam", "Pode solicitar exame de imagem"),
                ],
                "indexes": [
                    models.Index(fields=["-requested_at", "-id"], name="ris_requested_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation_key",), name="uniq_ris_operation_key"
                    )
                ],
            },
        ),
    ]
