# Generated by Django 6.1.1 on 2026-09-16 12:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pep", "0003_clinicalevolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientExportReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract_version",
                    models.CharField(default="patient-r4-v1", editable=False, max_length=32),
                ),
                ("content_sha256", models.CharField(editable=False, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pep.patient"
                    ),
                ),
            ],
            options={
                "permissions": [("export_patient", "Pode exportar cadastro mínimo de paciente")],
            },
        ),
    ]
