# Generated by Django 6.1.1 on 2026-09-18 15:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interoperability", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaboratorySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="Código técnico"),
                ),
                ("label", models.CharField(max_length=160, verbose_name="Descrição técnica")),
                ("active", models.BooleanField(default=True, verbose_name="Ativa")),
                ("operators", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LaboratoryInboxReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("size", models.PositiveIntegerField()),
                ("plaintext_sha256", models.CharField(max_length=64)),
                ("ciphertext_sha256", models.CharField(max_length=64)),
                ("ciphertext", models.BinaryField()),
                ("wrapped_key", models.TextField()),
                (
                    "encryption_version",
                    models.CharField(default="aegis1", editable=False, max_length=16),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="interoperability.laboratorysource",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
                "permissions": [
                    ("view_lab_inbox", "Pode consultar caixa laboratorial"),
                    ("receive_lab_file", "Pode receber arquivo laboratorial"),
                ],
                "indexes": [
                    models.Index(fields=["-received_at", "-id"], name="lab_inbox_received_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "plaintext_sha256"), name="uniq_lab_source_digest"
                    )
                ],
            },
        ),
    ]
